<div>
    <?php if ($this->flashSession->has('success')): ?>
        <div class="alert alert-success">
            <?php foreach ($this->flashSession->getMessages('success') as $message): ?>
                <?= $message ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if ($this->flashSession->has('error')): ?>
        <div class="alert alert-danger">
            <?php foreach ($this->flashSession->getMessages('error') as $message): ?>
                <?= $message ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <h1>Créer une equipe :</h1>

    <?= $this->view->chefdeprojet ?>



</div>


<script>
    //Disable les checkbox apres avoir selectionner 3 developpeurs
    function limitCheckboxes(maxChecked) {
        const checkboxes = document.querySelectorAll('.checkbox');
        let checkedCount = 0;

        checkboxes.forEach(checkbox => {
            if (checkbox.checked) {
                checkedCount++;
            }
        });

        if (checkedCount >= maxChecked) {
            checkboxes.forEach(checkbox => {
                if (!checkbox.checked) {
                    checkbox.disabled = true;
                }
            });
        } else {
            checkboxes.forEach(checkbox => {
                checkbox.disabled = false;
            });
        }
    }
</script>