<?php if (!isset($table) && !$table) { ?>
    <style>
        .maintenance {
            text-transform: uppercase;
            margin-bottom: 1rem;
            font-size: 3rem;
        }

        .container {
            display: table;
            margin: 0 auto;
            max-width: 1024px;
            width: 100%;
            height: 100%;
            align-content: center;
            position: relative;
            box-sizing: border-box;
        }

        .container .what-is-up {
            display: block;
            vertical-align: middle;
            text-align: center;
            box-sizing: border-box;
        }

        .container .what-is-up .spinny-cogs {
            display: block;
            margin-bottom: 2rem;
        }

        @-webkit-keyframes fa-spin-one {
            0% {
                transform: translateY(-2rem) rotate(0deg);
            }

            100% {
                transform: translateY(-2rem) rotate(-359deg);
            }
        }

        @keyframes fa-spin-one {
            0% {
                transform: translateY(-2rem) rotate(0deg);
            }

            100% {
                transform: translateY(-2rem) rotate(-359deg);
            }
        }

        .fa-spin-one,
        .container .what-is-up .spinny-cogs .fa:nth-of-type(1) {
            -webkit-animation: fa-spin-one 1s infinite linear;
            animation: fa-spin-one 1s infinite linear;
        }

        @-webkit-keyframes fa-spin-two {
            0% {
                transform: translateY(-0.5rem) translateY(1rem) rotate(0deg);
            }

            100% {
                transform: translateY(-0.5rem) translateY(1rem) rotate(-359deg);
            }
        }

        @keyframes fa-spin-two {
            0% {
                transform: translateY(-0.5rem) translateY(1rem) rotate(0deg);
            }

            100% {
                transform: translateY(-0.5rem) translateY(1rem) rotate(-359deg);
            }
        }

        .fa-spin-two,
        .container .what-is-up .spinny-cogs .fa:nth-of-type(3) {
            -webkit-animation: fa-spin-two 2s infinite linear;
            animation: fa-spin-two 2s infinite linear;
        }
    </style>

    <div class="container">
        <div class="what-is-up">

            <div class="spinny-cogs">
                <i class="fa fa-cog" aria-hidden="true"></i>
                <i class="fa fa-5x fa-cog fa-spin" aria-hidden="true"></i>
                <i class="fa fa-3x fa-cog" aria-hidden="true"></i>
            </div>
            <h1 class="maintenance">En cours de maintenance</h1>
            <h2>Nos développeurs travaillent dur pour mettre à jour votre système. Veuillez patienter pendant que nous
                faisons cela. Nous avons également créé des engrenages en rotation pour vous distraire</h2>
        </div>
    </div>
<?php } else { ?>
    <?php echo $table; ?>
<?php } ?>