<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/ebebeaafad.js" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
<?php echo $this->view->getPartial("partials/header") ?>
<button class="btn bg-white pb-5 pt-3" data-bs-toggle="offcanvas" data-bs-target="#offcanvas" role="button">
    <i class="fa-solid fa-bars fa-2xl"></i>
</button>
<div class="container" style="margin-bottom:20em;">

    <?php echo $this->getContent(); ?>
</div>


</body>
</html>