<!DOCTYPE html>
<html lang="en">
<head>
    {{ partial('head') }}
</head>
<body>
<div class="container">
    <h1>Welcome to Phalcon!</h1>
    <p>This is your main content section.</p>
    <?php
    /** @var \Phalcon\Models\Collaborateur $t */
    foreach ($this->view->getVar("myColab") as $t) { ?>
        <p>name : <?= $t->getPrenomNom() ?> </p>
        <p>prime : <?= $t->getPrimeEmbauche() ?></p>
    <?php } ?>
k</div>
{{ partial('footer') }}
</body>
</html>





