<div class="container">
    <?php if ($this->flashSession->has('success')): ?>
        <div class="alert alert-success">
            <?php foreach ($this->flashSession->getMessages('success') as $message): ?>
                <?= $message ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php if ($this->flashSession->has('error')): ?>
        <div class="alert alert-danger">
            <?php foreach ($this->flashSession->getMessages('error') as $message): ?>
                <?= $message ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    <?php if(!empty($table)) { ?>
    <?php echo $table; ?>
    <?php } else { ?>
    <h1 class="text-center">Il n'y a aucunes équipes</h1>
    <?php } ?>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header flex-column">
                        <i class="fa-solid fa-trash  fa-4x mb-2" style="color: #ff0000;"></i>
                        <h1 class="modal-title fs-5" id="deleteModalLabel">Are you sure?</h1>
                </div>
                <div class="modal-body">
                    Do you really want to delete these records? This process cannot be undone.
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="#"  id="delete-button" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modifyModal" tabindex="-1" aria-labelledby="modifyModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header flex-column">
                    <h1 class="modal-title fs-5" id="modifyModalLabel">Choisissez un nouveau collaborateur</h1>
                </div>
                <div class="modal-body">
                    <form action="/phalcon/equipe/modifyDevInTeam">
                        <select name="newDevName" class="form-select" aria-label="Default select example">
                        </select>
                        <input type="hidden" id="devId" name="devId" value=""><br>
                        <input type="hidden" id="teamId" name="teamId" value=""><br>
                        <input type="submit" value="Submit">
                    </form>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    addEventListener("DOMContentLoaded", (event) => {

        /** Ajoute un evenement sur le boutton modifier et recupere l'id de l'equipe */
        document.addEventListener('click', function(event) {
            if (event.target.classList.contains('button-for-modify')) {
                const teamId = event.target.getAttribute('data-team');
                const cdpId = event.target.getAttribute('data-cdp');
                document.getElementById("teamId").value =   teamId;
                document.getElementById("devId").value = event.target.getAttribute('data-dev');
                getAvailableDevs(teamId, cdpId);
            }
        });

        /** Recupere les developpeurs  */
        function getAvailableDevs(teamId, cdpId) {
            fetch(`/phalcon/equipe/getAvailableDevs?teamid=${teamId}&cdpid=${cdpId}`)
                .then(response => response.json())
                .then(data => populateDropdown(data));
        }

        function populateDropdown(data) {
            let selectModal = document.querySelector('.form-select');
            selectModal.innerHTML = "";  // clear existing options

            data.developers.forEach(dev => {
                let option = document.createElement('option');
                option.value = dev.id;
                option.text = `${dev.name} (${dev.competence})`;
                selectModal.appendChild(option);
            });
        }

        // Recupere l'id de l'equipe et appel la fonction qui modifie l'équipe
        function handleModifyClick() {
            let myDevId = this.dataset.modifyTeam;
            let myTeamId = this.dataset.team;
            console.log(myTeamId);
            document.getElementById("modify-button").href = `/phalcon/equipe/modify?devid=${myDevId}&teamid=${myTeamId}`;
        }


        // Recupere l'id de l'equipe et appel la fonction qui supprime l'équipe
        function handleDeleteClick() {
            let myTeamId = this.dataset.deleteTeam;
            document.getElementById("delete-button").href = `/phalcon/equipe/delete?teamid=${myTeamId}`;
        }


        Array.from(document.getElementsByClassName("button-for-modify")).forEach(button => {
            button.addEventListener("click", handleModifyClick);
        });

        Array.from(document.getElementsByClassName("btn-for-delete")).forEach(button => {
            button.addEventListener("click", handleDeleteClick);
        });



    });


</script>