<div class="container">
    <?php if(!empty($table)) { ?>
    <?php echo $table; ?>
    <?php } else { ?>
    <h1 class="text-center">Il n'y a aucune équipe</h1>
    <?php } ?>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header flex-column">
                        <i class="fa-solid fa-trash  fa-4x mb-2" style="color: #ff0000;"></i>
                        <h1 class="modal-title fs-5" id="deleteModalLabel">Are you sure?</h1>
                </div>
                <div class="modal-body">
                    Do you really want to delete these records? This process cannot be undone.
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="#"  id="delete-button" class="btn btn-danger">Delete</a>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modifyModal" tabindex="-1" aria-labelledby="modifyModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header flex-column">
                    <h1 class="modal-title fs-5" id="modifyModalLabel">Choisissez un nouveau collaborateur</h1>
                </div>
                <div class="modal-body">
                    <select class="form-select" aria-label="Default select example">
                    </select>
                </div>
                <div class="modal-footer justify-content-center">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <a href="#"  id="modify-button" class="btn btn-success">Modifier</a>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    addEventListener("DOMContentLoaded", (event) => {

        /** Ajoute un evenement sur le boutton modifier et recupere l'id de l'equipe */
        document.addEventListener('click', function(event) {
            if (event.target.classList.contains('button-for-modify')) {
                const teamId = event.target.getAttribute('data-team');
                getAvailableDevs(teamId);
            }
        });

        /** Recupere les developpeurs  */
        function getAvailableDevs(teamId) {
            fetch(`/phalcon/equipe/getAvailableDevs?teamid=${teamId}`)
                .then(response => response.json())
                .then(data => populateDropdown(data));
        }

        function populateDropdown(data) {
            let selectElem = document.querySelector('.form-select');
            selectElem.innerHTML = "";  // clear existing options

            data.developers.forEach(dev => {
                let option = document.createElement('option');
                option.value = dev.id;
                option.text = dev.name;
                selectElem.appendChild(option);
            });
        }

        // Recupere l'id de l'equipe et appel la fonction qui modifie l'équipe
        function handleModifyClick() {
            let myDevId = this.dataset.modifyTeam;
            let myTeamId = this.dataset.team;
            console.log(myTeamId);
            document.getElementById("modify-button").href = `/phalcon/equipe/modify?devid=${myDevId}&teamid=${myTeamId}`;
        }


        // Recupere l'id de l'equipe et appel la fonction qui supprime l'équipe
        function handleDeleteClick() {
            let myTeamId = this.dataset.deleteTeam;
            document.getElementById("delete-button").href = `/phalcon/equipe/delete?teamid=${myTeamId}`;
        }


        Array.from(document.getElementsByClassName("button-for-modify")).forEach(button => {
            button.addEventListener("click", handleModifyClick);
        });

        Array.from(document.getElementsByClassName("btn-for-delete")).forEach(button => {
            button.addEventListener("click", handleDeleteClick);
        });



    });


</script>